version: '3.10'

services:
  web:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - qdrant

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - my-db:/var/lib/postgresql/data postgres

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data

configs:
  qdrant_config:
    content: |
      log_level: INFO      

volumes:
  my-db: